app/WordSearch.php, app/Words.php, database/migrations/2020_07_02_220104_create_words_table.php, database/migrations/2020_07_02_220854_create_word_searches_table.php
Se incorpora los modelos WordSearch y Words con su respectivas migraciones.
=> #7 Modelo y migración WordSearch

app/Word.php, database/seeds/DatabaseSeeder.php, database/seeds/MultipleChoicesTableSeeder.php, database/seeds/WordSearchesTableSeeder.php, database/seeds/WordsTableSeeder.php
-Modifico el nombre del modelo Words a Word
-Crear el seeder para Word
-Crear el seeder para WordSearch
-Crear el seeder para MultipleChoice
=> #14 Crear Seeding para MultipleChoice y WordSearch

database/seeds/DatabaseSeeder.php, database/seeds/StudentsTableSeeder.php, database/seeds/TestsTableSeeder.php
Actualicé mi rama dev y volví a crear los seeders
=> #16 Creación de seeders para Tests y Students

app/Http/Controllers/AdministratorController.php, app/Http/Kernel.php, app/Http/Middleware/Cors.php, routes/api.php
=> #17 Rutas y Controlador de Administrator

app/Http/Controllers/CrosswordController.php, app/Http/Controllers/QuestionController.php, app/Http/Resources/Question.php, app/Http/Resources/QuestionCollection.php, database/seeds/CrosswordsTableSeeder.php, routes/api.php
Se implemento los recursos para Question 
Se creo el controlador para Crossword pero no contiene código
=> 19 Creación de rutas y controladores para Question

app/Http/Controllers/MultipleChoiceController.php, app/Http/Resources/MultipleChoice.php, app/Http/Resources/MultipleChoiceCollection.php, routes/api.php
También, se especifican las rutas para MultipleChoice
=> #20 Creación de Controlador y recurso para Multiple Choice

app/Http/Controllers/CompleteController.php, app/Http/Resources/Complete.php, app/Http/Resources/CompleteCollection.php, routes/api.php
Se creó las rutas y controladores para el Complete
Se creó los recursos para Complete
=> #21 Rutas y Controladores para Complete

app/Activity.php, app/Complete.php, app/Crossword.php, app/MultipleChoice.php, app/Word.php, app/WordSearch.php, database/migrations/2020_07_23_001643_add_activity_id_column_complete.php, database/migrations/2020_07_23_134731_add_activity_id_column_multiple_choice.php, database/migrations/2020_07_23_135358_add_activity_id_column_crossword.php, database/migrations/2020_07_23_140245_add_word_search_id_column_word.php, database/seeds/ActivitiesTableSeeder.php, database/seeds/CompletesTableSeeder.php, database/seeds/CrosswordsTableSeeder.php, database/seeds/DatabaseSeeder.php, database/seeds/MultipleChoicesTableSeeder.php, database/seeds/UsersTableSeeder.php, database/seeds/WordSearchesTableSeeder.php, database/seeds/WordsTableSeeder.php
En esta tarea se realizó la relación de las siguientes tablas:
word_searches - words (1-M)
activities - completes (1-1)
activities - multiple_choices (1-1)
activities - crosswords (1-1)
=> #28 relationships Part 1

app/Activity.php, app/ActivityTest.php, app/Test.php, app/User.php, app/WordSearch.php, database/migrations/2020_07_01_223903_create_activities_table.php, database/migrations/2020_07_05_010145_create_tests_table.php, database/migrations/2020_07_26_165325_add_activity_id_column_word_search.php, database/migrations/2020_07_26_175957_create_activity_tests_table.php, database/migrations/2020_07_26_180615_add_activity_id_column_activity_tests.php, database/migrations/2020_07_26_183559_add_test_id_column_activity_tests.php, database/seeds/ActivitiesTestsTableSeeder.php, database/seeds/DatabaseSeeder.php, database/seeds/UsersTableSeeder.php, database/seeds/WordSearchesTableSeeder.php
Relaciones:
- Activity-Word Search
- Modelo activity_tests con sus relaciones hacia tests y activity
- Relación de activity_tests con user (student)
Modificaciones
- Método down() de test y activity para poder resetear las migraciones
=> #31 Relaciones Parte 3

app/Course.php, app/Http/Controllers/CourseController.php, app/Http/Controllers/TestController.php, app/Http/Controllers/UserController.php, database/seeds/CoursesTableSeeder.php, routes/api.php
Validación de: Courses y Tests
La validación de Teachers y Students ya están en el controlador de Users
=> 32 Validación parte 1

app/Http/Controllers/ActivityController.php, app/Http/Controllers/CompleteController.php, app/Http/Controllers/MultipleChoiceController.php, app/Http/Controllers/QuestionController.php, app/Http/Controllers/TestController.php, app/Http/Controllers/WordController.php, app/Http/Controllers/WordSearchController.php, database/seeds/CourseStudentSeeder.php, database/seeds/DatabaseSeeder.php, database/seeds/StudentActivityTestSeeder.php
Se realiza la validacion de los datos en todas las tablas.
Las rutas combinadas de Activites-WordShearch y Word (y las siguiente), hacen falta
=> #33 Validacion de Datos parte 2

app/Http/Resources/Course.php, app/Http/Resources/Test.php, app/Http/Resources/User.php
Se modificaron los resources de course, test y user para mostrar solo lo necesario para el usuario teacher.
=> #76 Clausulas condicionales para las rutas de teacher

app/Http/Resources/Activity.php, app/Http/Resources/Complete.php, app/Http/Resources/Course.php, app/Http/Resources/MultipleChoice.php, app/Http/Resources/Question.php, app/Http/Resources/Word.php
Quitar visualización de timestamps en:
- Activity
- Complete
- Course
- Multiple Choice
- Question
=> #79 modifiación de recursos

app/Http/Controllers/CrosswordController.php, app/Http/Resources/Activity.php, app/Http/Resources/Course.php, app/Http/Resources/Crossword.php, app/Http/Resources/CrosswordCollection.php, app/Http/Resources/Test.php, app/Http/Resources/Word.php, app/Http/Resources/WordSearch.php, database/seeds/UsersTableSeeder.php, routes/api.php
Se añade coleciones a los recursos de Crosswords y Word Search
Se añade una linea en la coleccion de Courses con autenticacion para Students
No se consigue implementar la visualizacion de 
las actividades por test
y las actividades segun el tipo
=> #78 Modificacion de Recursos

.idea/dictionaries/Fredd.xml, app/Http/Controllers/CourseController.php, app/Http/Controllers/UserController.php, routes/api.php
Se edito el controlador de user para el inicio de sesión
*Revisar el controlador de Course para el nuevo endpoint
=> Arreglos login

app/Http/Controllers/CourseController.php, app/Http/Controllers/UserController.php, app/Http/Resources/Course.php, app/Policies/CoursePolicy.php, app/User.php, database/seeds/CoursesTableSeeder.php, routes/api.php
No se pudo implementar la ruta de user/courses.
=> Cambios en la Api

app/Http/Controllers/CourseController.php, database/migrations/2020_07_03_124628_create_courses_table.php, database/seeds/CoursesTableSeeder.php
Se crearon las rutas para que el estudiante pueda a unirse a un curso, para que el docente pueda ver los cursos que creo y para que los estudiantes puedan ver los cursos donde están inscritos.
En el controlador de joinCourse se estableció las validaciones necesarias.
Se modificó el seeder de courses para que solo los profesores puedan crear cursos
=> #89 Nuevas rutas

app/Http/Controllers/CourseController.php, app/Http/Resources/User.php, database/migrations/2020_07_03_124628_create_courses_table.php
Se asignan los últimos 7 dígitos del al uniqid para que no exista repetidos,
El valor de la campo code es varchar deben ejecutar migraciones y seeders,
se modifica el recurso User para que devuelva el token respectivo.
=> Codigo automatico de Curso

app/Http/Controllers/CourseController.php, app/Http/Resources/Course.php, routes/api.php
Se añade una ruta para los estudiantes, para obtener infromacion de cada curso.
Se corrige el metodo de post por get en el documento api.php
=> Metodo corregido

app/Http/Controllers/ActivityController.php, app/Http/Controllers/CompleteController.php, app/Http/Controllers/TestController.php, routes/api.php
Se creo una ruta donde se establece la relación polimórfica entre Activity y Complete
=> #93 Ruta para crear Activity-Complete
